// Action Types

export const ACTION_TYPES = {
    GET_LECONS : 'GET_LECONS',
    GET_LECON : 'GET_LECON',
    POST_LECON :  'POST_LECON',
    DELETE_LECON : 'DELETE_LECON',

    GET_CLIENTS : 'GET_CLIENTS',
    GET_CLIENT : 'GET_CLIENT',
    POST_CLIENT : 'POST_CLIENT',
    DELETE_CLIENT : 'DELETE_CLIENT'
}
