// Action Types

export const ACTION_TYPES = {
    GET_LECONS : 'GET_LECONS',
    GET_LECON : 'GET_LECON',
    POST_LECON :  'POST_LECON',
    DELETE_LECON : 'DELETE_LECON',

    GET_CLIENTS : 'GET_CLIENTS',
    GET_CLIENT : 'GET_CLIENT',
    POST_CLIENT : 'POST_CLIENT',
    DELETE_CLIENT : 'DELETE_CLIENT',

    GET_MONITEURS : 'GET_MONITEURS',
    GET_MONITEUR : 'GET_MONITEUR',
    POST_MONITEUR : 'POST_MONITEUR',
    DELETE_MONITEUR : 'DELETE_MONITEUR',
    AUTH_MONITEUR : 'AUTH_MONITEUR',
    UNAUTH_MONITEUR : 'UNAUTH_MONITEUR',
    AUTH_ERROR : 'AUTH_ERROR',

    GET_VEHICULES : 'GET_VEHICULES',
    GET_VEHICULE : 'GET_VEHICULE',
    POST_VEHICULE : 'POST_VEHICULE',
    DELETE_VEHICULE : 'DELETE_VEHICULE',

    GET_MESSAGES : 'GET_MESSAGES',
    GET_MESSAGE : 'GET_MESSAGE',
    POST_MESSAGE : 'POST_MESSAGE',
    DELETE_MESSAGE : 'DELETE_MESSAGE',

    ERROR : 'ERROR'
}
